import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const portfolioSummaryMcpTool = defineProjectionMcpTool({
  name: "portfolio.query_portfolio_summary",
  title: "Query Portfolio Summary",
  description: "@DESCRIPTION_TODO",
  context: "Portfolio",
  slice: "Portfolio Summary",
  projectionName: "PortfolioSummary",
});
