import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const accountViewMcpTool = defineProjectionMcpTool({
  name: "account.query_account_view",
  title: "Query accountView",
  description: "@DESCRIPTION_TODO",
  context: "Account",
  slice: "accountView",
  projectionName: "AccountView",
});
