import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const accountViewMcpTool = defineProjectionMcpTool({
  name: "account.query_account_view",
  title: "Query accountView",
  description: "Query the AccountView read model to retrieve account details including name and currency. Use this tool when an agent needs to look up account information by account ID.",
  context: "Account",
  slice: "accountView",
  projectionName: "AccountView",
});
