import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const portfolioExposureMcpTool = defineProjectionMcpTool({
  name: "portfolio_query_portfolio_exposure",
  title: "Query portfolioExposure",
  description: "@DESCRIPTION_TODO",
  context: "Portfolio",
  slice: "portfolioExposure",
  projectionName: "PortfolioExposure",
});
