#!/usr/bin/env python3
"""Build PR body text from confidence and repair results.

Usage:
  python3 .ci/build_pr_body.py \
    --context Portfolio \
    --slices "addloantoportfolio,assessloanrisk" \
    --base-branch main

Prints the full PR body to stdout.
"""
import json, argparse

BAND_EMOJI = {"HIGH": "\U0001f7e2", "MEDIUM": "\U0001f7e1", "LOW": "\U0001f7e0", "BLOCKED": "\U0001f534"}

def load_json(path):
    try:
        return json.load(open(path))
    except Exception:
        return None

def build_confidence_section(conf):
    if not conf:
        return ""
    ctx = conf.get("context_summary", {})
    slices = conf.get("slices", [])
    band = ctx.get("worst_band", "UNKNOWN")
    lines = []
    lines.append(f'## Confidence: {BAND_EMOJI.get(band, "")} {band} (avg {ctx.get("average_score", "?")})')
    lines.append("")
    lines.append("| Slice | Score | Band | Recommendation |")
    lines.append("|-------|-------|------|----------------|")
    for s in slices:
        e = BAND_EMOJI.get(s.get("band", ""), "")
        lines.append(f'| {s["slice_name"]} | {s["score"]} | {e} {s["band"]} | {s["recommended_action"]} |')
    for s in slices:
        if s.get("reasons") and s["reasons"] != ["All checks passed"]:
            lines.append(f'')
            lines.append(f'**{s["slice_name"]}** flags:')
            for r in s["reasons"]:
                lines.append(f"- {r}")
    return "\n".join(lines)

def build_healing_section(repair):
    if not repair or repair.get("total_attempted", 0) == 0:
        return ""
    lines = ["## Self-Healing", ""]
    lines.append(f'**{repair["total_repaired"]}/{repair["total_attempted"]}** repairs succeeded ({repair["total_ai_used"]} used AI)')
    lines.append("")
    for r in repair.get("repairs", []):
        icon = "\u2705" if r["repaired"] else "\u274c"
        lines.append(f'- {icon} **{r["slice_name"]}**: {r["strategy_used"]} \u2014 {r["details"]}')
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--context", required=True)
    parser.add_argument("--slices", required=True)
    parser.add_argument("--base-branch", required=True)
    args = parser.parse_args()

    conf = load_json("/tmp/confidence.json")
    repair = load_json("/tmp/repair-results.json")

    confidence_body = build_confidence_section(conf)
    healing_body = build_healing_section(repair)

    body = f"""## Summary
Auto-generated slice implementations for the **{args.context}** context.

**Slices:** {args.slices}
**Target:** `{args.base_branch}`

## Commits
1. **Split** \u2014 slice definitions extracted from config.json (deterministic)
2. **Scaffold** \u2014 TypeScript boilerplate generated by evdb-scaffold (deterministic, no AI)
3. **Business logic** \u2014 predicates, handler branching, enrichment filled by Claude Code (AI)

{confidence_body}

{healing_body}

## Review checklist
- [ ] Predicate logic in `gwts.ts` matches domain rules
- [ ] Command handler branching covers all spec scenarios
- [ ] Generated field computations are correct
- [ ] Tests pass and cover edge cases

Generated with evdb CI pipeline (v2 \u2014 self-healing)"""

    print(body)

if __name__ == "__main__":
    main()
