#!/usr/bin/env python3
"""Build PR stats comment from Claude stats, confidence, and classification data.

Usage:
  python3 .ci/build_pr_comment.py \
    --context Portfolio \
    --slices "addloantoportfolio,assessloanrisk" \
    --duration "5m 30s" \
    --run-id 12345 \
    --run-number 42 \
    --repo "owner/repo"

Prints comment body to stdout.
"""
import json, argparse

def load_json(path):
    try:
        return json.load(open(path))
    except Exception:
        return None

def load_stats():
    try:
        stats = {}
        for line in open("/tmp/claude-stats.txt"):
            k, v = line.strip().split("=", 1)
            stats[k] = v
        return stats
    except Exception:
        return {}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--context", required=True)
    parser.add_argument("--slices", required=True)
    parser.add_argument("--duration", default="")
    parser.add_argument("--run-id", default="")
    parser.add_argument("--run-number", default="")
    parser.add_argument("--repo", default="")
    parser.add_argument("--worst-band", default="")
    parser.add_argument("--avg-score", default="")
    parser.add_argument("--repaired", default="0")
    args = parser.parse_args()

    stats = load_stats()
    summary = ""
    try:
        summary = open("/tmp/claude-summary.txt").read()
    except Exception:
        summary = "No output captured"

    classification = load_json("/tmp/classification.json")
    class_section = ""
    if classification and classification.get("total_failures", 0) > 0:
        lines = ["### Failure Classification", ""]
        lines.append("| Slice | Class | Deterministic |")
        lines.append("|-------|-------|---------------|")
        for c in classification["classifications"]:
            det = "\u2713" if c["deterministic"] else "\u2717"
            lines.append(f'| {c["slice_name"]} | `{c["failure_class"]}` | {det} |')
        class_section = "\n".join(lines)

    run_link = f"[#{args.run_number}](https://github.com/{args.repo}/actions/runs/{args.run_id})" if args.run_id else ""

    comment = f"""## Generation Stats

| Metric | Value |
|--------|-------|
| Context | **{args.context}** |
| Slices | `{args.slices}` |
| Duration | **{args.duration}** |
| API time | {stats.get('api_time_s', '0')}s |
| Turns | {stats.get('num_turns', '0')} |
| Input tokens | {stats.get('input_tokens', '0')} |
| Output tokens | {stats.get('output_tokens', '0')} |
| Total tokens | {stats.get('total_tokens', '0')} |
| Cost | **${stats.get('cost', '0')}** |
| Confidence | **{args.worst_band}** (avg {args.avg_score}) |
| Repairs | {args.repaired} applied |
| Workflow run | {run_link} |

### Claude Code Summary

{summary}

{class_section}

---
*Generated by evdb CI pipeline v2 (self-healing)*"""

    print(comment)

if __name__ == "__main__":
    main()
