import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const portfolioLoanDetailsMcpTool = defineProjectionMcpTool({
  name: "portfolio_query_portfolio_loan_details",
  title: "Query Portfolio Loan Details",
  description: "Queries the current risk details for all loans within a portfolio. Returns per-loan data including risk band, credit rating, expected loss, capital requirement, and worst-case loss figures derived from the most recent LoanRiskAssessed event. Call this tool when an agent needs to inspect the current risk profile of loans in a given portfolio.",
  context: "Portfolio",
  slice: "Portfolio Loan Details",
  projectionName: "PortfolioLoanDetails",
});
