import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const portfolioLoanDetailsMcpTool = defineProjectionMcpTool({
  name: "portfolio.query_portfolio_loan_details",
  title: "Query Portfolio Loan Details",
  description: "Queries detailed loan-level data for a portfolio, including risk metrics, credit ratings, loss estimates, and borrower information for each loan. Use this tool when an agent needs to retrieve individual loan risk assessments or review the composition and risk profile of a specific portfolio.",
  context: "Portfolio",
  slice: "Portfolio Loan Details",
  projectionName: "PortfolioLoanDetails",
});
