import { defineProjectionMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const loanSubmissionStatusMcpTool = defineProjectionMcpTool({
  name: "portfolio_query_loan_submission_status",
  title: "Query Loan submission status",
  description: "@DESCRIPTION_TODO",
  context: "Portfolio",
  slice: "Loan submission status",
  projectionName: "LoanSubmissionStatus",
});
