import { defineCommandMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const createAccountMcpTool = defineCommandMcpTool({
  name: "account.create_account",
  title: "create account",
  description: "Creates a new account and emits an accountCreated event. Call this tool when an agent needs to register a new account with a specified name and currency.",
  context: "Account",
  slice: "create account",
  basePath: "/api/account",
  routePath: "/create-account",
  inputSchema: {
    type: "object",
    required: ["currency", "name"],
    additionalProperties: false,
    properties: {
      currency: { type: "string" },
      name: { type: "string" },
    },
  },
  outputSchema: {
    type: "object",
    required: ["streamId", "emittedEventTypes"],
    properties: {
      streamId: { type: "string" },
      emittedEventTypes: { type: "array", items: { type: "string" } },
    },
  },
  emits: ["accountCreated"],
  annotations: { idempotentHint: true },
});
