import { defineCommandMcpTool } from "#abstractions/mcp/defineMcpTool.js";

// @generated by evdb-scaffold — description is filled in by implement_slice.py's AI step.
export const addLoanToPortfolioMcpTool = defineCommandMcpTool({
  name: "portfolio_add_loan_to_portfolio",
  title: "Add Loan to Portfolio",
  description: "Adds a loan to a portfolio after validating the loan amount and portfolio credit rating constraints. Emits LoanAddedToPortfolio if the loan is accepted, or LoanRejectedFromPortfolio if the loan amount is non-positive or the new loan's credit rating would breach the portfolio's existing credit quality. Call this tool when an agent needs to submit a loan for inclusion in a portfolio.",
  context: "Portfolio",
  slice: "Add Loan To Portfolio",
  basePath: "/api/portfolio",
  routePath: "/add-loan-to-portfolio",
  inputSchema: {
    type: "object",
    required: ["portfolioId", "borrowerName", "creditRating", "interestRate", "loanAmount", "maturityDate"],
    additionalProperties: false,
    properties: {
      portfolioId: { type: "string" },
      borrowerName: { type: "string" },
      creditRating: { type: "string" },
      interestRate: { type: "number" },
      loanAmount: { type: "number" },
      maturityDate: { type: "string", format: "date" },
    },
  },
  outputSchema: {
    type: "object",
    required: ["streamId", "emittedEventTypes"],
    properties: {
      streamId: { type: "string" },
      emittedEventTypes: { type: "array", items: { type: "string" } },
    },
  },
  emits: ["LoanRejectedFromPortfolio", "LoanAddedToPortfolio"],
  annotations: { idempotentHint: true },
});
